### ISSUE TITLE
doesn't support defaults

### ISSUE THREAD

**Issue by disconn3ct** [jaconi-io/flux-envsubst#19]
flux permits defaulting:
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    owners: ${devteam:=testteam}
```
Setting `devteam`:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
spec:
  ...
  postBuild:
    substitute:
      devteam: "greenteam"
```
the flux result is `owners: greenteam`. With the value missing (no substitutions) it receives `owners: testteam`

Trying this pattern results in:
`Error: variable substitution failed for Namespace /${namespace}: variable "devteam" is not set`
