### ISSUE TITLE
Defaulting does not work

### ISSUE THREAD

**Issue by jnodorp-jaconi** [jaconi-io/flux-envsubst#20]
`kustomization.yaml`:
```yaml
resources:
  - ./namespace.yaml
```

`namespace.yaml`:
```
apiVersion: v1
kind: Namespace
metadata:
  name: foo
  labels:
    foo: ${bar:baz}
```

Execute:
```shell
customise build . | flux-envsubst
```

Expected: Label `foo` is `baz`.

Actual: `Error: variable substitution failed for Namespace /foo: variable "bar" is not set`
